#########################################################
# MCBansProxy Configuration File
# - Main Site: http://mcbans.com
# - Support Desk: http://support.mcbans.com
# - Community: http://forums.mcbans.com
##

# apiKey:
#   Your servers apiKey can be found in your account dashboard http://my.mcbans.com/servers
apiKey: ''

# minRep:
#   Minimum reputation a user may have before being disallowed access to the server.
#   DEFAULT: 3 (-1 to disable)
minRep: 3
minRepMessage: 'Your reputation is below this servers threshold!'

#########################################################
# Alternate Account Limiting (Premium server only!)
#   Limits the how alternate accounts affect connectability to the server
##

# enableMaxAlts:
#   Activate limiting maximum number of alt accounts (true/false)
#   Limits the maximum number of alt accounts a user may have before
#   being denied access to the server.
#   DEFAULT: false
enableMaxAlts: false

# maxAlts:
#   Maximum number of alternate accounts allowed before denying user
#   DEFAULT: 2
maxAlts: 2
maxAltsMessage: 'You have more alt accounts than this server allows!'

#########################################################
# Miscellaneous Settings
#   Settings that don't have a part of any other sections
##

# timeout:
#   Timeout (in seconds) value of connecting mcbans API server while player joining the server.
#   DEFAULT: 10 (10 Seconds)
timeout: 10
unavailableMessage: 'Unavailable MCBans Service! Please try again later!'

# failsafe:
#   If set to true, disallow access to the server when can't auth players,
#   unavailable mcbans api servers (timeout), internal plugin error etc.
#   DEFAULT: false
failsafe: false

# isDebug:
#   Enable additional debug messages throughout the plugin
#   DEFAULT: false
isDebug: false